apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: {{ .Values.mongodb.name }}
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecret.name }}
                key: mongodb-admin-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecret.name }}
                key: mongodb-admin-password
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.mongodbService.name }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  type: ClusterIP
  ports:
  - name: {{ .Values.mongodbService.portName }}
    port: {{ .Values.mongodbService.port }}
    targetPort: {{ .Values.mongodb.port }}
