apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoExpress.name }}
  labels:
    app: {{ .Values.mongoExpress.name }}
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongoExpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoExpress.name }}
    spec:
      containers:
      - name: {{ .Values.mongoExpress.name }}
        image: {{ .Values.mongoExpress.image }}
        ports:
          -  containerPort: {{ .Values.mongoExpress.port }}
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecret.name }}
                key: mongodb-admin-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongoSecret.name }}
                key: mongodb-admin-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.mongoConfigmap.name }}
                key: mongodb-server-url
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.mongoExpressService.name }}
spec:
  selector:
    app: {{ .Values.mongoExpress.name }}
  type:  LoadBalancer
  ports:
  - name: {{ .Values.mongoExpressService.portName }}
    port: {{ .Values.mongoExpressService.port }}
    targetPort: {{ .Values.mongoExpress.port }}
    nodePort: {{ .Values.mongoExpressService.nodePort }}
                  